export default Strings = {
  awesome: "Awesome!",
  setupAccountStep0Message: "Your profile look great, ready to look around.",
  scanCard: "Scan your Card",
  dontHaveCard: "I don't have my Card",
  continue: "Continue",
  myIndexIs: "My index is",
  myNameIs: "My name is",
  myBirthDayIs: "My birthday is",
  myGenderIs: "My gender",
  myScannedCard: "My scanned card",
  genderMale: "Male",
  genderFemale: "Female",
  country: "Country",
  region: "Region",
  playGolfAt: "I play Golf at",
  tapToSelect: "Tap to select",
  confirm: "Confirm",
  cancel: "Cancel",
  selectCardImage: "Select your card",
  myBestPictureIs: "My best picture is"
}