export default Strings = {
  awesome: "Awesome!",
  registration: "Registration",
  connection: "Connection",
  setupAccountStep0Message: "Your profile look great, ready to look around.",
  scanCard: "Scan your Card",
  dontHaveCard: "I don't have my Card",
  continue: "Continue",
  myIndexIs: "My index is",
  myNameIs: "My name is",
  myBirthDayIs: "My birthday is",
  myGenderIs: "My gender",
  myScannedCard: "My scanned card",
  genderMale: "Male",
  genderFemale: "Female",
  country: "Country",
  region: "Region",
  playGolfAt: "I play Golf at",
  tapToSelect: "Tap to select",
  confirm: "Confirm",
  cancel: "Cancel",
  selectCardImage: "Select your card",
  myBestPictureIs: "My best picture is",
  activeLocation: "Active location service",
  activeLocationMessage: "Your location will be used to help you break into matches near you and access the geolocation based options available. Click on \"Learn more\" to get more information",
  learnMore: "Learn more",
  active: "Active",
  enterEmail: "Enter a valid email address",
  checkEmail: "Verify your email address",
  discover: "Discover",
  settings: "Settings",
  getGGSubscription: "Get GG Subscription",
  getGGCredit: "Get More GG Credits",
  settingsNotification: "Notifications",
  settingsNewChallengesPut: "New Challenges Put",
  settingsNewChallengesChipAndPut: "New Challenges Chip & Put",
  settingsNewChallenges9Holes: "New Challenges 9 Holes",
  settingsNewChallenges18Holes: "New Challenges 18 Holes",
  settingsMessages: "Messages",
  settingsValidationCard: "Validation Card",
  settingsContactUs: "Contact us",
  settingsHelpAndSuppport: "Help & Support",
  settingsRateUs: "Rate Us",
  settingShareGG: "Share GG",
  settingsLegal: "Legal",
  settingsPrivacyPolicy: "Privacy Policy",
  settingsTermsOfService: "Term of Service",
  settingsLicenses: "Licenses",
  settingLogout: "Logout",
  settingDeleteAccount: "Delete Account",
  settingWebProfile: "Web profile",
  settingsUsername: "Username",
  settingsDiscover: "Discover settings",
  settingsLocation: "Location",
  settingsMaxDistance: "Maximum Distance",
  settingsGender: "Gender",
  settingsAgeRange: "Age Range",
  settingsIndexRange: "Index Range",
  settingsShowMeOnGG: "Show me on GG",
  settingsShowMeOnGGMessage: "Turning this on will show your profile to golfers near you.",
  settingSwipeWithFriends: "Swipe with Friends",
  settingSwipeWithFriendsMessage: "Turning this on will allow your friends to find you and invite you to play together.",
  registerWithFacebook: "Register with Facebook",
  registerWithGoogle: "Register with Google Account",
  registerWithEmail: "Register with your e-mail",
  or: "or",
  alreadyMember: "Already member? Connection"
}