export default Theme = {
  buttonPrimary: "#d66a28",
  buttonPrimary2: "#f4a77a",
  buttonSecondary: "#8D8D8D",
  textWhite: "#FFFFFF",
  textGray: "#BFBFBF",
  toolbarTitle: "#d66a28",
  separator: "#BFBFBF",
  sliderColor: "#d66a28",
  valid: "#AFF8DB",
  error: "red",
  tabBarBackground: "black",
  tabIconActive: "white",
  tabIconDeactive: "gray",
}