export const ADD_PLACE = 'ADD_PLACE'

export const GET_COUNTRIES_BEGIN = 'GET_COUNTRIES_BEGIN'
export const GET_COUNTRIES_FINISH = 'GET_COUNTRIES_FINISH'
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR'

export const GET_REGIONS_BEGIN = 'GET_REGIONS_BEGIN'
export const GET_REGIONS_FINISH = 'GET_REGIONS_FINISH'
export const GET_REGIONS_ERROR = 'GET_REGIONS_ERROR'

export const GET_CLUBS_BEGIN = 'GET_CLUBS_BEGIN'
export const GET_CLUBS_FINISH = 'GET_CLUBS_FINISH'
export const GET_CLUBS_ERROR = 'GET_CLUBS_ERROR'

export const LOGIN_BEGIN = 'LOGIN_BEGIN'
export const LOGIN_FINISH = 'LOGIN_FINISH'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const REGISTER_BEGIN = 'REGISTER_BEGIN'
export const REGISTER_FINISH = 'REGISTER_FINISH'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const GET_CHALLENGES_BEGIN = 'GET_CHALLENGES_BEGIN'
export const GET_CHALLENGES_FINISH = 'GET_CHALLENGES_FINISH'
export const GET_CHALLENGES_ERROR = 'GET_CHALLENGES_ERROR'