export const ADD_PLACE = 'ADD_PLACE'

export const GET_COUNTRIES_BEGIN = 'GET_COUNTRIES_BEGIN'
export const GET_COUNTRIES_FINISH = 'GET_COUNTRIES_FINISH'
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR'

export const GET_REGIONS_BEGIN = 'GET_REGIONS_BEGIN'
export const GET_REGIONS_FINISH = 'GET_REGIONS_FINISH'
export const GET_REGIONS_ERROR = 'GET_REGIONS_ERROR'

export const GET_CLUBS_BEGIN = 'GET_CLUBS_BEGIN'
export const GET_CLUBS_FINISH = 'GET_CLUBS_FINISH'
export const GET_CLUBS_ERROR = 'GET_CLUBS_ERROR'

export const LOGIN_BEGIN = 'LOGIN_BEGIN'
export const LOGIN_FINISH = 'LOGIN_FINISH'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const REGISTER_BEGIN = 'REGISTER_BEGIN'
export const REGISTER_FINISH = 'REGISTER_FINISH'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const GET_CHALLENGES_BEGIN = 'GET_CHALLENGES_BEGIN'
export const GET_CHALLENGES_FINISH = 'GET_CHALLENGES_FINISH'
export const GET_CHALLENGES_ERROR = 'GET_CHALLENGES_ERROR'

export const GET_PENDING_MATCHES = {
  BEGIN: 'GET_PENDING_MATCHES_BEGIN',
  FINISH: 'GET_PENDING_MATCHES_FINISH',
  ERROR: 'GET_PENDING_MATCHES_ERROR'
}

export const GET_PLAYED_MATCHES = {
  BEGIN: 'GET_PLAYED_MATCHES_BEGIN',
  FINISH: 'GET_PLAYED_MATCHES_FINISH',
  ERROR: 'GET_PLAYED_MATCHES_ERROR'
}

export const GET_SCORES = {
  BEGIN: 'GET_SCORES_BEGIN',
  FINISH: 'GET_SCORES_FINISH',
  ERROR: 'GET_SCORES_ERROR'
}

export const GET_MESSAGES = {
  BEGIN: 'GET_MESSAGES_BEGIN',
  FINISH: 'GET_MESSAGES_FINISH',
  ERROR: 'GET_MESSAGES_ERROR'
}

export const GET_NOTIFICATIONS = {
  NEW: {
    BEGIN: 'GET_NOTIFICATIONS_NEW_BEGIN',
    FINISH: 'GET_NOTIFICATIONS_NEW_FINISH',
    ERROR: 'GET_NOTIFICATIONS_NEW_ERROR'
  },
  HISTORY: {
    BEGIN: 'GET_NOTIFICATIONS_HISTORY_BEGIN',
    FINISH: 'GET_NOTIFICATIONS_HISTORY_FINISH',
    ERROR: 'GET_NOTIFICATIONS_HISTORY_ERROR'
  }
}

export const GET_RANKING = {
  FAVORITE: {
    BEGIN: 'GET_FAVORITE_RANKING_BEGIN',
    FINISH: 'GET_FAVORITE_RANKING_FINISH',
    ERROR: 'GET_FAVORITE_RANKING_ERROR'
  },
  ALL: {
    BEGIN: 'GET_ALL_RANKING_BEGIN',
    FINISH: 'GET_ALL_RANKING_FINISH',
    ERROR: 'GET_ALL_RANKING_ERROR'
  }
}

export const GET_PROFILE = {
  BEGIN: 'GET_PROFILE_BEGIN',
  FINISH: 'GET_PROFILE_FINISH',
  ERROR: 'GET_PROFILE_ERROR'
}